package com.titleverify.titleverify_ai.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.titleverify.titleverify_ai.dto.RuleResultDto;
import com.titleverify.titleverify_ai.dto.TitleComparisonDto;
import com.titleverify.titleverify_ai.dto.TitleVerificationResultDto;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class VerificationReportService {

    private static final Color COLOR_PRIMARY = new Color(15, 23, 42);
    private static final Color COLOR_MUTED = new Color(100, 116, 139);
    private static final Color COLOR_BORDER = new Color(203, 213, 225);
    private static final Color COLOR_ROW_ALT = new Color(248, 250, 252);
    private static final Color COLOR_REC_BG = new Color(240, 253, 244);
    private static final Color COLOR_REC_BORDER = new Color(187, 247, 208);
    private static final Color COLOR_REC_TEXT = new Color(22, 101, 52);
    private static final Color COLOR_DISCLAIMER_BG = new Color(241, 245, 249);

    private static final Font FONT_TITLE = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, COLOR_PRIMARY);
    private static final Font FONT_SUBTITLE = FontFactory.getFont(FontFactory.HELVETICA, 9.5f, COLOR_MUTED);
    private static final Font FONT_META_TAG = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8.5f, COLOR_MUTED);
    private static final Font FONT_SECTION = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, COLOR_PRIMARY);
    private static final Font FONT_BODY_BOLD = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8.5f, COLOR_PRIMARY);
    private static final Font FONT_BODY = FontFactory.getFont(FontFactory.HELVETICA, 8.5f, new Color(51, 65, 85));
    private static final Font FONT_TABLE_HEADER = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8f, Color.WHITE);
    private static final Font FONT_TABLE_CELL = FontFactory.getFont(FontFactory.HELVETICA, 8f, new Color(15, 23, 42));
    private static final Font FONT_TABLE_CELL_BOLD = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8f, new Color(15, 23, 42));
    private static final Font FONT_DISCLAIMER = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 7.5f, new Color(71, 85, 105));

    private static final String EXACT_DISCLAIMER =
            "DISCLAIMER: This report is generated by TitleVerify AI as an automated pre-submission screening prototype. " +
            "Risk scores, confidence values, and similarity signals are advisory and do not represent official PRGI approval decisions or legal clearance.";

    public byte[] generatePdfReport(TitleComparisonDto comparisonDetails) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 36f, 36f, 36f, 36f);

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            addDocumentHeader(document, comparisonDetails);
            addApplicationProfile(document, comparisonDetails);
            addExecutiveSummary(document, comparisonDetails);
            addComparisonTable(document, comparisonDetails);
            addPerTitleDetails(document, comparisonDetails);
            addDisclaimer(document);

            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new IllegalStateException("Failed to generate PDF verification report", e);
        }
    }

    private void addDocumentHeader(Document document, TitleComparisonDto comparisonDetails) throws DocumentException {
        Long appId = (comparisonDetails != null) ? comparisonDetails.getApplicationId() : null;
        String refId = (appId != null) ? "TV-APP-" + appId : "TV-APP-N/A";

        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100f);
        headerTable.setWidths(new float[]{70f, 30f});
        headerTable.setSpacingAfter(12f);

        PdfPCell leftCell = new PdfPCell();
        leftCell.setBorder(Rectangle.NO_BORDER);
        leftCell.setPadding(0);
        Paragraph title = new Paragraph("TitleVerify AI — Pre-Submission Title Clearance Report", FONT_TITLE);
        title.setSpacingAfter(2f);
        Paragraph subtitle = new Paragraph("Automated Title Verification & Regulatory Feasibility Assessment", FONT_SUBTITLE);
        leftCell.addElement(title);
        leftCell.addElement(subtitle);
        headerTable.addCell(leftCell);

        PdfPCell rightCell = new PdfPCell();
        rightCell.setBorder(Rectangle.NO_BORDER);
        rightCell.setPadding(0);
        rightCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        Paragraph refPara = new Paragraph("Report Reference: " + refId, FONT_META_TAG);
        refPara.setAlignment(Element.ALIGN_RIGHT);
        Paragraph verPara = new Paragraph("Verification Engine Version: v1.0", FONT_META_TAG);
        verPara.setAlignment(Element.ALIGN_RIGHT);
        rightCell.addElement(refPara);
        rightCell.addElement(verPara);
        headerTable.addCell(rightCell);

        document.add(headerTable);

        PdfPTable divider = new PdfPTable(1);
        divider.setWidthPercentage(100f);
        divider.setSpacingAfter(10f);
        PdfPCell lineCell = new PdfPCell();
        lineCell.setFixedHeight(2f);
        lineCell.setBackgroundColor(COLOR_PRIMARY);
        lineCell.setBorder(Rectangle.NO_BORDER);
        divider.addCell(lineCell);
        document.add(divider);
    }

    private void addApplicationProfile(Document document, TitleComparisonDto comparisonDetails) throws DocumentException {
        Paragraph heading = new Paragraph("APPLICATION PROFILE", FONT_SECTION);
        heading.setSpacingAfter(6f);
        document.add(heading);

        PdfPTable profileTable = new PdfPTable(4);
        profileTable.setWidthPercentage(100f);
        profileTable.setWidths(new float[]{20f, 30f, 20f, 30f});
        profileTable.setSpacingAfter(14f);

        addProfileField(profileTable, "Application ID:", comparisonDetails != null && comparisonDetails.getApplicationId() != null ? "#" + comparisonDetails.getApplicationId() : "N/A");
        addProfileField(profileTable, "Publication Type:", comparisonDetails != null ? safeString(comparisonDetails.getPublicationType()) : "N/A");
        addProfileField(profileTable, "Language:", comparisonDetails != null ? safeString(comparisonDetails.getLanguage()) : "N/A");
        addProfileField(profileTable, "Periodicity:", comparisonDetails != null ? safeString(comparisonDetails.getPeriodicity()) : "N/A");
        addProfileField(profileTable, "State:", comparisonDetails != null ? safeString(comparisonDetails.getState()) : "N/A");
        addProfileField(profileTable, "District:", comparisonDetails != null ? safeString(comparisonDetails.getDistrict()) : "N/A");
        addProfileField(profileTable, "Submission Date:", comparisonDetails != null ? safeString(comparisonDetails.getFormattedCreatedAt()) : "N/A");
        addProfileField(profileTable, "Total Titles:", comparisonDetails != null && comparisonDetails.getVerificationResults() != null ? String.valueOf(comparisonDetails.getVerificationResults().size()) : "0");

        document.add(profileTable);
    }

    private void addProfileField(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, FONT_BODY_BOLD));
        labelCell.setBackgroundColor(COLOR_ROW_ALT);
        labelCell.setBorderColor(COLOR_BORDER);
        labelCell.setPadding(4.5f);
        table.addCell(labelCell);

        PdfPCell valCell = new PdfPCell(new Phrase(value, FONT_BODY));
        valCell.setBorderColor(COLOR_BORDER);
        valCell.setPadding(4.5f);
        table.addCell(valCell);
    }

    private void addExecutiveSummary(Document document, TitleComparisonDto comparisonDetails) throws DocumentException {
        Paragraph heading = new Paragraph("EXECUTIVE SUMMARY", FONT_SECTION);
        heading.setSpacingAfter(6f);
        document.add(heading);

        PdfPTable summaryBox = new PdfPTable(1);
        summaryBox.setWidthPercentage(100f);
        summaryBox.setSpacingAfter(14f);

        PdfPCell boxCell = new PdfPCell();
        boxCell.setBackgroundColor(COLOR_REC_BG);
        boxCell.setBorderColor(COLOR_REC_BORDER);
        boxCell.setPadding(8f);

        if (comparisonDetails != null && comparisonDetails.getRecommendedTitle() != null) {
            TitleVerificationResultDto rec = comparisonDetails.getRecommendedTitle();
            int optNum = comparisonDetails.getRecommendedOptionNumber();

            Font recTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11, COLOR_REC_TEXT);
            Paragraph recTitlePara = new Paragraph("Recommended Choice: Option #" + optNum + " — " + safeString(rec.getProposedTitle()), recTitleFont);
            recTitlePara.setSpacingAfter(4f);
            boxCell.addElement(recTitlePara);

            PdfPTable kpiTable = new PdfPTable(4);
            kpiTable.setWidthPercentage(100f);
            kpiTable.setWidths(new float[]{25f, 25f, 25f, 25f});
            kpiTable.setSpacingAfter(4f);

            addKpiCell(kpiTable, "Decision", safeString(rec.getFinalDecision()), getDecisionColor(rec.getFinalDecision()));
            addKpiCell(kpiTable, "Risk Score", formatScore(rec.getRiskScore()), COLOR_PRIMARY);
            addKpiCell(kpiTable, "Risk Level", safeString(rec.getRiskLevel()), COLOR_PRIMARY);
            addKpiCell(kpiTable, "Approval Confidence", formatConfidence(rec.getApprovalConfidence()), COLOR_REC_TEXT);
            boxCell.addElement(kpiTable);

            if (comparisonDetails.getRecommendationExplanation() != null && !comparisonDetails.getRecommendationExplanation().trim().isEmpty()) {
                Paragraph expPara = new Paragraph("Recommendation Explanation: " + comparisonDetails.getRecommendationExplanation().trim(), FONT_BODY);
                expPara.setSpacingBefore(4f);
                boxCell.addElement(expPara);
            }
        } else {
            boxCell.addElement(new Paragraph("No recommendation available — no proposed titles submitted.", FONT_BODY));
        }

        summaryBox.addCell(boxCell);
        document.add(summaryBox);
    }

    private void addKpiCell(PdfPTable table, String label, String value, Color valColor) {
        PdfPCell cell = new PdfPCell();
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setPadding(2f);
        Paragraph lbl = new Paragraph(label, FONT_META_TAG);
        Font valFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9.5f, valColor);
        Paragraph val = new Paragraph(value, valFont);
        cell.addElement(lbl);
        cell.addElement(val);
        table.addCell(cell);
    }

    private void addComparisonTable(Document document, TitleComparisonDto comparisonDetails) throws DocumentException {
        Paragraph heading = new Paragraph("PROPOSED TITLES COMPARISON", FONT_SECTION);
        heading.setSpacingAfter(6f);
        document.add(heading);

        PdfPTable table = new PdfPTable(11);
        table.setWidthPercentage(100f);
        table.setWidths(new float[]{7f, 21f, 10f, 8f, 9f, 9f, 8f, 7f, 7f, 7f, 17f});
        table.setSpacingAfter(14f);

        String[] headers = {
                "Option", "Proposed Title", "Decision", "Risk Score", "Risk Level",
                "Confidence", "BM25", "Fuzzy", "Phonetic", "Semantic", "Closest Match"
        };
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, FONT_TABLE_HEADER));
            cell.setBackgroundColor(COLOR_PRIMARY);
            cell.setBorderColor(COLOR_PRIMARY);
            cell.setPadding(5f);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            table.addCell(cell);
        }

        List<TitleVerificationResultDto> results = (comparisonDetails != null) ? comparisonDetails.getVerificationResults() : null;
        if (results != null && !results.isEmpty()) {
            for (int i = 0; i < results.size(); i++) {
                TitleVerificationResultDto res = results.get(i);
                boolean isAlt = (i % 2 == 1);
                Color rowBg = isAlt ? COLOR_ROW_ALT : Color.WHITE;

                addTableCell(table, "#" + (i + 1), FONT_TABLE_CELL_BOLD, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, safeString(res.getProposedTitle()), FONT_TABLE_CELL_BOLD, rowBg, Element.ALIGN_LEFT);
                addTableCell(table, safeString(res.getFinalDecision()), getDecisionFont(res.getFinalDecision()), rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatScore(res.getRiskScore()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, safeString(res.getRiskLevel()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatConfidence(res.getApprovalConfidence()), FONT_TABLE_CELL_BOLD, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatBm25(res.getHighestBm25Similarity()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatPercent(res.getHighestFuzzySimilarity()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatPercent(res.getHighestPhoneticSimilarity()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, formatPercent(res.getHighestSemanticSimilarity()), FONT_TABLE_CELL, rowBg, Element.ALIGN_CENTER);
                addTableCell(table, safeString(res.getClosestMatch()), FONT_TABLE_CELL, rowBg, Element.ALIGN_LEFT);
            }
        } else {
            PdfPCell emptyCell = new PdfPCell(new Phrase("No titles available for comparison.", FONT_BODY));
            emptyCell.setColspan(11);
            emptyCell.setPadding(8f);
            emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(emptyCell);
        }

        document.add(table);
    }

    private void addTableCell(PdfPTable table, String text, Font font, Color bg, int align) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setBorderColor(COLOR_BORDER);
        cell.setPadding(4f);
        cell.setHorizontalAlignment(align);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        table.addCell(cell);
    }

    private void addPerTitleDetails(Document document, TitleComparisonDto comparisonDetails) throws DocumentException {
        Paragraph heading = new Paragraph("PER-TITLE DETAILS", FONT_SECTION);
        heading.setSpacingAfter(6f);
        document.add(heading);

        List<TitleVerificationResultDto> results = (comparisonDetails != null) ? comparisonDetails.getVerificationResults() : null;
        if (results == null || results.isEmpty()) {
            Paragraph emptyPara = new Paragraph("No detailed title records to display.", FONT_BODY);
            emptyPara.setSpacingAfter(10f);
            document.add(emptyPara);
            return;
        }

        for (int i = 0; i < results.size(); i++) {
            TitleVerificationResultDto res = results.get(i);
            int optNum = i + 1;

            PdfPTable cardTable = new PdfPTable(1);
            cardTable.setWidthPercentage(100f);
            cardTable.setSpacingAfter(10f);

            PdfPCell cardCell = new PdfPCell();
            cardCell.setBorderColor(COLOR_BORDER);
            cardCell.setPadding(7f);
            cardCell.setBackgroundColor(Color.WHITE);

            Paragraph titleHeader = new Paragraph("Option #" + optNum + ": " + safeString(res.getProposedTitle()), FONT_BODY_BOLD);
            titleHeader.setSpacingAfter(4f);
            cardCell.addElement(titleHeader);

            PdfPTable metricsTable = new PdfPTable(4);
            metricsTable.setWidthPercentage(100f);
            metricsTable.setWidths(new float[]{25f, 25f, 25f, 25f});
            metricsTable.setSpacingAfter(4f);

            addDetailKpi(metricsTable, "Decision", safeString(res.getFinalDecision()), getDecisionColor(res.getFinalDecision()));
            addDetailKpi(metricsTable, "Risk Score", formatScore(res.getRiskScore()) + " / 100", COLOR_PRIMARY);
            addDetailKpi(metricsTable, "Risk Level", safeString(res.getRiskLevel()), COLOR_PRIMARY);
            addDetailKpi(metricsTable, "Approval Confidence", formatConfidence(res.getApprovalConfidence()), COLOR_PRIMARY);
            cardCell.addElement(metricsTable);

            PdfPTable signalsTable = new PdfPTable(2);
            signalsTable.setWidthPercentage(100f);
            signalsTable.setWidths(new float[]{50f, 50f});
            signalsTable.setSpacingAfter(4f);

            String bm25Text = formatBm25(res.getHighestBm25Similarity()) +
                    (res.getTopBm25Match() != null ? " (Match: " + res.getTopBm25Match() + ")" : "");
            String fuzzyText = formatPercent(res.getHighestFuzzySimilarity()) +
                    (res.getTopFuzzyMatch() != null ? " (Match: " + res.getTopFuzzyMatch() + ")" : "");
            String phoneticText = formatPercent(res.getHighestPhoneticSimilarity()) +
                    (res.getTopPhoneticMatch() != null ? " (Match: " + res.getTopPhoneticMatch() + ")" : "");
            String semanticText = formatPercent(res.getHighestSemanticSimilarity()) +
                    (res.getTopSemanticMatch() != null ? " (Match: " + res.getTopSemanticMatch() + ")" : "");

            addSignalRow(signalsTable, "BM25 Similarity:", bm25Text);
            addSignalRow(signalsTable, "Fuzzy Similarity:", fuzzyText);
            addSignalRow(signalsTable, "Phonetic Similarity:", phoneticText);
            addSignalRow(signalsTable, "Semantic Similarity:", semanticText);
            addSignalRow(signalsTable, "Closest Match:", safeString(res.getClosestMatch()));
            cardCell.addElement(signalsTable);

            Paragraph rulesHeading = new Paragraph("RULE FINDINGS:", FONT_BODY_BOLD);
            rulesHeading.setSpacingBefore(3f);
            rulesHeading.setSpacingAfter(2f);
            cardCell.addElement(rulesHeading);

            List<RuleResultDto> ruleResults = res.getRuleResults();
            long triggeredCount = (ruleResults != null) ? ruleResults.stream().filter(RuleResultDto::isTriggered).count() : 0;
            if (triggeredCount > 0) {
                for (RuleResultDto r : ruleResults) {
                    if (r.isTriggered()) {
                        String ruleLine = "• " + safeString(r.getRuleName()) + " [" + (r.getSeverity() != null ? r.getSeverity().name() : "WARNING") + "]: " +
                                safeString(r.getMessage()) + (r.getEvidence() != null ? " (Evidence: " + r.getEvidence() + ")" : "");
                        Paragraph rulePara = new Paragraph(ruleLine, FONT_BODY);
                        rulePara.setIndentationLeft(8f);
                        cardCell.addElement(rulePara);
                    }
                }
            } else {
                Paragraph cleanPara = new Paragraph("Compliant — no triggered rule findings.", FONT_BODY);
                cleanPara.setIndentationLeft(8f);
                cardCell.addElement(cleanPara);
            }

            if (res.getRecommendation() != null && !res.getRecommendation().trim().isEmpty()) {
                Paragraph recHeading = new Paragraph("RECOMMENDATION:", FONT_BODY_BOLD);
                recHeading.setSpacingBefore(4f);
                recHeading.setSpacingAfter(2f);
                cardCell.addElement(recHeading);

                Paragraph recText = new Paragraph(res.getRecommendation().trim(), FONT_BODY);
                recText.setIndentationLeft(8f);
                cardCell.addElement(recText);
            }

            cardTable.addCell(cardCell);
            document.add(cardTable);
        }
    }

    private void addDetailKpi(PdfPTable table, String label, String value, Color color) {
        PdfPCell cell = new PdfPCell();
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setPadding(2f);
        cell.addElement(new Paragraph(label, FONT_META_TAG));
        Font valFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8.5f, color);
        cell.addElement(new Paragraph(value, valFont));
        table.addCell(cell);
    }

    private void addSignalRow(PdfPTable table, String label, String value) {
        PdfPCell cell = new PdfPCell();
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setPadding(1.5f);
        Phrase p = new Phrase();
        p.add(new Chunk(label + " ", FONT_BODY_BOLD));
        p.add(new Chunk(value, FONT_BODY));
        cell.addElement(p);
        table.addCell(cell);
    }

    private void addDisclaimer(Document document) throws DocumentException {
        PdfPTable disclTable = new PdfPTable(1);
        disclTable.setWidthPercentage(100f);
        disclTable.setSpacingBefore(8f);

        PdfPCell cell = new PdfPCell();
        cell.setBackgroundColor(COLOR_DISCLAIMER_BG);
        cell.setBorderColor(COLOR_BORDER);
        cell.setPadding(6f);

        Paragraph disclPara = new Paragraph(EXACT_DISCLAIMER, FONT_DISCLAIMER);
        cell.addElement(disclPara);
        disclTable.addCell(cell);

        document.add(disclTable);
    }

    private Color getDecisionColor(String decision) {
        if ("ACCEPT".equalsIgnoreCase(decision)) {
            return COLOR_REC_TEXT;
        } else if ("REVIEW".equalsIgnoreCase(decision)) {
            return new Color(180, 83, 9);
        } else {
            return new Color(185, 28, 28);
        }
    }

    private Font getDecisionFont(String decision) {
        return FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8f, getDecisionColor(decision));
    }

    private String formatPercent(Double value) {
        if (value == null) {
            return "N/A";
        }
        return String.format("%.1f%%", value * 100);
    }

    private String formatConfidence(Double value) {
        if (value == null) {
            return "N/A";
        }
        return String.format("%.1f%%", value);
    }

    private String formatScore(Double value) {
        if (value == null) {
            return "N/A";
        }
        return String.format("%.1f", value);
    }

    private String formatBm25(Double value) {
        if (value == null) {
            return "N/A";
        }
        return String.format("%.2f", value);
    }

    private String safeString(String value) {
        return (value == null || value.trim().isEmpty()) ? "N/A" : value.trim();
    }
}
